name: currency
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  auto_route: ^7.8.4
  get_it: ^7.6.4
  injectable: ^2.3.1
  dartz: ^0.10.1
  currency_converter: ^0.0.5
  freezed_annotation: ^2.4.1
  country_icons: ^2.0.2
  country_flags: ^2.1.1

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  injectable_generator: ^2.4.1
  freezed: ^2.4.1

flutter:
  uses-material-design: true
  generate: true
